"""Type stubs for deap.base module."""

from typing import Any, Callable, Sequence, TypeVar

class Fitness:
    """Fitness object for minimization/maximization."""

    weights: tuple[float, ...]
    values: tuple[float, ...]
    @property
    def valid(self) -> bool: ...
    def __init__(self) -> None: ...
    def __le__(self, other: Fitness) -> bool: ...
    def __lt__(self, other: Fitness) -> bool: ...
    def __ge__(self, other: Fitness) -> bool: ...
    def __gt__(self, other: Fitness) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def dominates(self, other: Fitness, use_weights: bool = ...) -> bool: ...
    def getValues(self) -> tuple[float, ...]: ...
    def setValues(self, value: Sequence[float]) -> None: ...

class Individual(list[Any]):
    """Individual for evolutionary strategies."""

    fitness: Fitness
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ConstrainedFitness(Fitness):
    """Constrained fitness allowing penalties."""

    ...

T = TypeVar("T")

class Toolbox:
    """Toolbox for storing and executing registered functions."""
    def __init__(self) -> None: ...
    def register(
        self, alias: str, function: Callable[..., Any], *args: Any, **kwargs: Any
    ) -> None: ...
    def unregister(self, alias: str) -> None: ...
    def __getattr__(self, name: str) -> Callable[..., Any]: ...
    def __call__(self, name: str, *args: Any, **kwargs: Any) -> Any: ...
    def select_best(self, individuals: Sequence[T], k: int) -> list[T]: ...
    def select(self, individuals: Sequence[T], k: int) -> list[T]: ...
