"""Type stubs for deap.tools module."""

from typing import Any, Callable, Optional, Sequence

class Logbook:
    """Logbook for tracking statistics during evolution."""

    chapters: dict[str, Any]
    header: list[str]
    def __init__(self) -> None: ...
    def select(self, key: str) -> Sequence[Any]: ...
    def record(self, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...  # Support len()
    def __getitem__(self, index: int) -> Any: ...  # Support indexing
    def __iter__(self) -> Any: ...  # Support iteration
    @property
    def stream(self) -> str: ...  # Pretty-print statistics

class HallOfFame:
    """Hall of Fame for storing best individuals."""
    def __init__(self, k: int) -> None: ...
    def update(self, population: Sequence[Any]) -> None: ...
    def items(self) -> Sequence[Any]: ...
    def __getitem__(self, index: int) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...  # Make iterable for enumerate()

class ParetoFront(HallOfFame):
    """Pareto front archive."""
    def __init__(self, similar: Callable[[Any, Any], bool] = ...) -> None: ...
    def update(self, population: Sequence[Any]) -> None: ...
    def items(self) -> Sequence[Any]: ...

class Statistics:
    """Statistics for tracking population metrics."""

    fields: list[str]
    def __init__(self, key: Optional[Callable[[Any], Any]] = ...) -> None: ...
    def register(
        self, alias: str, function: Callable[[Any], Any], **kwargs: Any
    ) -> None: ...
    def compile(self, population: Sequence[Any]) -> dict[str, Any]: ...

class MultiStatistics:
    """Multiple statistics trackers."""
    def __init__(self) -> None: ...
    def register(self, name: str, stats: Statistics) -> None: ...

class History:
    """History tracking for evolution."""
    def __init__(self) -> None: ...
    def update(self, population: Sequence[Any]) -> None: ...
    def getGenealogy(self, ind: Any) -> Sequence[Any]: ...

def crossover(ind1: Any, ind2: Any) -> tuple[Any, Any]: ...
def mutate(individual: Any) -> tuple[Any, ...]: ...
def selBest(
    individuals: Sequence[Any],
    k: int,
    fit_attr: str = ...,
) -> Sequence[Any]: ...
def selWorst(
    individuals: Sequence[Any],
    k: int,
    fit_attr: str = ...,
) -> Sequence[Any]: ...
def selTournament(
    individuals: Sequence[Any],
    k: int,
    tournsize: int,
    fit_attr: str = ...,
) -> Sequence[Any]: ...
def selDoubleTournament(
    individuals: Sequence[Any],
    k: int,
    fitness_size: int = ...,
    parsimony_size: float = ...,
    fitness_first: bool = ...,
    fit_attr: str = ...,
) -> Sequence[Any]: ...
def sortFitness(
    individuals: Sequence[Any],
    key: Callable[[Any], Any] = ...,
    reverse: bool = ...,
) -> list[Any]: ...
def sortMultiObjective(
    individuals: Sequence[Any],
    k: int,
) -> list[Any]: ...
def feasible(individual: Any) -> bool: ...
def median(seq: Sequence[float]) -> float: ...
def initRepeat(container: type, func: Callable[[], Any], n: int) -> Any: ...
def initIterate(container: type, func: Callable[[], Any], *args: Any) -> Any: ...
def initCycle(container: type, func: Callable[[], Any], n: int) -> Any: ...
