"""Type stubs for tables (PyTables) library."""

from typing import Any

class File:
    """HDF5 file object."""
    def __init__(self, filename: str, mode: str = ..., **kwargs: Any) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> File: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def get_node(self, where: str) -> Any: ...
    def create_table(
        self, where: str, name: str, description: Any, **kwargs: Any
    ) -> Any: ...
    def remove_node(self, where: str, name: str) -> None: ...
    root: Any

def open_file(filename: str, mode: str = ..., **kwargs: Any) -> File: ...
